package kz.bee.bip.syncchannel.v10.interfaces;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * Интерфейс для работы с синхронным каналом
 *
 * This class was generated by Apache CXF 4.0.3
 * 2024-02-28T17:57:50.079+06:00
 * Generated source version: 4.0.3
 *
 */
@WebService(targetNamespace = "http://bip.bee.kz/SyncChannel/v10/Interfaces", name = "ISyncChannel")
@XmlSeeAlso({kz.bee.bip.syncchannel.v10.types.request.ObjectFactory.class, kz.bee.bip.common.v10.types.ObjectFactory.class, kz.bee.bip.syncchannel.v10.types.response.ObjectFactory.class, kz.bee.bip.syncchannel.v10.types.ObjectFactory.class})
public interface ISyncChannel {

    /**
     * Метод отправки сообщения по синхронному каналу
     */
    @WebMethod(operationName = "SendMessage")
    @RequestWrapper(localName = "SendMessage", targetNamespace = "http://bip.bee.kz/SyncChannel/v10/Types", className = "kz.bee.bip.syncchannel.v10.types.SendMessage")
    @ResponseWrapper(localName = "SendMessageResponse", targetNamespace = "http://bip.bee.kz/SyncChannel/v10/Types", className = "kz.bee.bip.syncchannel.v10.types.SendMessageResponse")
    @WebResult(name = "response", targetNamespace = "")
    public kz.bee.bip.syncchannel.v10.types.response.SyncSendMessageResponse sendMessage(

        @WebParam(name = "request", targetNamespace = "")
        kz.bee.bip.syncchannel.v10.types.request.SyncSendMessageRequest request
    ) throws SendMessageSendMessageFaultMsg;
}
