<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions name="SyncChannelHttp_Service" targetNamespace="http://bip.bee.kz/SyncChannel/v10/Interfaces/Binding2" xmlns:Port_0="http://bip.bee.kz/SyncChannel/v10/Interfaces" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:this="http://bip.bee.kz/SyncChannel/v10/Interfaces/Binding2" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:import location="ISyncChannel.wsdl" namespace="http://bip.bee.kz/SyncChannel/v10/Interfaces"/>
  <wsdl:binding name="SyncChannelHttpBinding" type="Port_0:ISyncChannel">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="SendMessage">
      <soap:operation soapAction=""/>
      <wsdl:input name="SendMessageRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="SendMessageResponse">
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="sendMessageFault">
        <soap:fault name="sendMessageFault" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="ISyncChannelHttpService">
    <wsdl:port binding="this:SyncChannelHttpBinding" name="SyncChannelHttpPort">
      <soap:address location="http://localhost:9080/SerrviceSampleTypesWeb/sca/SyncChannelService"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>