
package kz.bee.bip.asyncchannel.v10.interfaces;

import jakarta.xml.ws.WebFault;


/**
 * Ошибка
 *
 * This class was generated by Apache CXF 4.0.3
 * 2024-02-28T14:28:52.424+06:00
 * Generated source version: 4.0.3
 */

@WebFault(name = "getMessageStatusFault1_getMessageStatusFault", targetNamespace = "http://bip.bee.kz/AsyncChannel/v10/Types")
public class GetMessageStatusGetMessageStatusFaultMsg extends Exception {
    public static final long serialVersionUID = 1L;

    private kz.bee.bip.common.v10.types.ErrorInfo faultInfo;

    public GetMessageStatusGetMessageStatusFaultMsg() {
        super();
    }

    public GetMessageStatusGetMessageStatusFaultMsg(String message) {
        super(message);
    }

    public GetMessageStatusGetMessageStatusFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public GetMessageStatusGetMessageStatusFaultMsg(String message, kz.bee.bip.common.v10.types.ErrorInfo getMessageStatusFault1GetMessageStatusFault) {
        super(message);
        this.faultInfo = getMessageStatusFault1GetMessageStatusFault;
    }

    public GetMessageStatusGetMessageStatusFaultMsg(String message, kz.bee.bip.common.v10.types.ErrorInfo getMessageStatusFault1GetMessageStatusFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = getMessageStatusFault1GetMessageStatusFault;
    }

    public kz.bee.bip.common.v10.types.ErrorInfo getFaultInfo() {
        return this.faultInfo;
    }
}
