
package kz.bee.bip.asyncchannel.v10.interfaces;

import jakarta.xml.ws.WebFault;


/**
 * ошибка
 *
 * This class was generated by Apache CXF 4.0.3
 * 2024-02-28T17:57:49.896+06:00
 * Generated source version: 4.0.3
 */

@WebFault(name = "getMessagesFault1_getMessagesFault", targetNamespace = "http://bip.bee.kz/AsyncChannel/v10/Types")
public class GetMessagesGetMessagesFaultMsg extends Exception {
    public static final long serialVersionUID = 1L;

    private kz.bee.bip.common.v10.types.ErrorInfo faultInfo;

    public GetMessagesGetMessagesFaultMsg() {
        super();
    }

    public GetMessagesGetMessagesFaultMsg(String message) {
        super(message);
    }

    public GetMessagesGetMessagesFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public GetMessagesGetMessagesFaultMsg(String message, kz.bee.bip.common.v10.types.ErrorInfo getMessagesFault1GetMessagesFault) {
        super(message);
        this.faultInfo = getMessagesFault1GetMessagesFault;
    }

    public GetMessagesGetMessagesFaultMsg(String message, kz.bee.bip.common.v10.types.ErrorInfo getMessagesFault1GetMessagesFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = getMessagesFault1GetMessagesFault;
    }

    public kz.bee.bip.common.v10.types.ErrorInfo getFaultInfo() {
        return this.faultInfo;
    }
}
