package kz.bee.bip.asyncchannel.v10.interfaces;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * Интерфейс сервиса на ШЭП, для работы с асинхронным каналом
 *
 * This class was generated by Apache CXF 4.0.3
 * 2024-02-28T14:28:52.439+06:00
 * Generated source version: 4.0.3
 *
 */
@WebService(targetNamespace = "http://bip.bee.kz/AsyncChannel/v10/Interfaces", name = "IAsyncChannel")
@XmlSeeAlso({kz.bee.bip.asyncchannel.v10.types.ObjectFactory.class, kz.bee.bip.common.v10.types.ObjectFactory.class})
public interface IAsyncChannel {

    /**
     * Метод выборки сообщений с ШЭП по следующим параметрам:
     * -идентификатору сообщения+получателю(только для запрасившего)+идентификатору сервиса
     * -идентификатору цепочки сообщений+получателю(только для запрасившего)+идентификатору сервиса
     * -получателю(только для запрасившего)+идентификатору сервиса
     */
    @WebMethod
    @RequestWrapper(localName = "getMessages", targetNamespace = "http://bip.bee.kz/AsyncChannel/v10/Types", className = "kz.bee.bip.asyncchannel.v10.types.GetMessages")
    @ResponseWrapper(localName = "getMessagesResponse", targetNamespace = "http://bip.bee.kz/AsyncChannel/v10/Types", className = "kz.bee.bip.asyncchannel.v10.types.GetMessagesResponse")
    @WebResult(name = "response", targetNamespace = "")
    public kz.bee.bip.asyncchannel.v10.types.AsyncGetMessagesResponse getMessages(

        @WebParam(name = "request", targetNamespace = "")
        kz.bee.bip.asyncchannel.v10.types.AsyncGetMessagesRequest request
    ) throws GetMessagesGetMessagesFaultMsg;

    /**
     * Метод отправки уведомления на ШЭП о доставке или не доставке сообщения н
     */
    @WebMethod
    @RequestWrapper(localName = "sendDeliveryNotification", targetNamespace = "http://bip.bee.kz/AsyncChannel/v10/Types", className = "kz.bee.bip.asyncchannel.v10.types.SendDeliveryNotification")
    @ResponseWrapper(localName = "sendDeliveryNotificationResponse", targetNamespace = "http://bip.bee.kz/AsyncChannel/v10/Types", className = "kz.bee.bip.asyncchannel.v10.types.SendDeliveryNotificationResponse")
    @WebResult(name = "response", targetNamespace = "")
    public kz.bee.bip.asyncchannel.v10.types.AsyncSendDeliveryNotificationResponse sendDeliveryNotification(

        @WebParam(name = "request", targetNamespace = "")
        kz.bee.bip.asyncchannel.v10.types.AsyncSendDeliveryNotificationRequest request
    ) throws SendDeliveryNotificationSendDeliveryNotificationFaultMsg;

    /**
     * Метод получения статуса сообщения с ШЭП
     */
    @WebMethod
    @RequestWrapper(localName = "getMessageStatus", targetNamespace = "http://bip.bee.kz/AsyncChannel/v10/Types", className = "kz.bee.bip.asyncchannel.v10.types.GetMessageStatus")
    @ResponseWrapper(localName = "getMessageStatusResponse", targetNamespace = "http://bip.bee.kz/AsyncChannel/v10/Types", className = "kz.bee.bip.asyncchannel.v10.types.GetMessageStatusResponse")
    @WebResult(name = "response", targetNamespace = "")
    public kz.bee.bip.asyncchannel.v10.types.AsyncGetMessageStatusResponse getMessageStatus(

        @WebParam(name = "request", targetNamespace = "")
        kz.bee.bip.asyncchannel.v10.types.AsyncGetMessageStatusRequest request
    ) throws GetMessageStatusGetMessageStatusFaultMsg;

    /**
     * Метод для отправки сообщений на асинхронный канал ШЭП
     */
    @WebMethod
    @RequestWrapper(localName = "sendMessage", targetNamespace = "http://bip.bee.kz/AsyncChannel/v10/Types", className = "kz.bee.bip.asyncchannel.v10.types.SendMessage")
    @ResponseWrapper(localName = "sendMessageResponse", targetNamespace = "http://bip.bee.kz/AsyncChannel/v10/Types", className = "kz.bee.bip.asyncchannel.v10.types.SendMessageResponse")
    @WebResult(name = "response", targetNamespace = "")
    public kz.bee.bip.asyncchannel.v10.types.AsyncSendMessageResponse sendMessage(

        @WebParam(name = "request", targetNamespace = "")
        kz.bee.bip.asyncchannel.v10.types.AsyncSendMessageRequest request
    ) throws SendMessageSendMessageFaultMsg;
}
