package kz.bee.bip.asyncchannel.v10.interfaces.binding;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;
import kz.bee.bip.asyncchannel.v10.interfaces.IAsyncChannel;

/**
 * This class was generated by Apache CXF 4.0.3
 * 2024-02-28T14:28:52.459+06:00
 * Generated source version: 4.0.3
 *
 */
@WebServiceClient(name = "AsyncChannelHttpService",
                  wsdlLocation = "file:/Volumes/Dis/projects/otus/lessons/esb-isna-integration/src/main/resources/wsdl/AsyncChannel/v10/Interfaces/AsyncChannelHttp_Service.wsdl",
                  targetNamespace = "http://bip.bee.kz/AsyncChannel/v10/Interfaces/Binding")
public class AsyncChannelHttpService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://bip.bee.kz/AsyncChannel/v10/Interfaces/Binding", "AsyncChannelHttpService");
    public final static QName AsyncChannelHttpPort = new QName("http://bip.bee.kz/AsyncChannel/v10/Interfaces/Binding", "AsyncChannelHttpPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/Volumes/Dis/projects/otus/lessons/esb-isna-integration/src/main/resources/wsdl/AsyncChannel/v10/Interfaces/AsyncChannelHttp_Service.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(AsyncChannelHttpService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/Volumes/Dis/projects/otus/lessons/esb-isna-integration/src/main/resources/wsdl/AsyncChannel/v10/Interfaces/AsyncChannelHttp_Service.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public AsyncChannelHttpService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AsyncChannelHttpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AsyncChannelHttpService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public AsyncChannelHttpService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public AsyncChannelHttpService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public AsyncChannelHttpService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns IAsyncChannel
     */
    @WebEndpoint(name = "AsyncChannelHttpPort")
    public IAsyncChannel getAsyncChannelHttpPort() {
        return super.getPort(AsyncChannelHttpPort, IAsyncChannel.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IAsyncChannel
     */
    @WebEndpoint(name = "AsyncChannelHttpPort")
    public IAsyncChannel getAsyncChannelHttpPort(WebServiceFeature... features) {
        return super.getPort(AsyncChannelHttpPort, IAsyncChannel.class, features);
    }

}
